### ISSUE TITLE
[Enhancement] Remove `final` from `enum` type variables

### ISSUE THREAD

**Issue by 1chooo** [1chooo/uml-editor#15]
According to the article "[Why can't a Java enum be final?](https://stackoverflow.com/questions/9891613/why-cant-a-java-enum-be-final)", the answer states, "Java does not allow you to create a class that extends an enum type. Therefore, enums themselves are always final, so using the final keyword is superfluous." Consequently, we can remove the `final` keyword from our `enum` type variables.

https://github.com/1chooo/uml-editor/blob/47e2956a56edaa2450cb4c94be9f3ea70beae0c5/src/Utils/Config.java#L1-L13

https://github.com/1chooo/uml-editor/blob/47e2956a56edaa2450cb4c94be9f3ea70beae0c5/src/Utils/Helper.java#L1-L12

https://github.com/1chooo/uml-editor/blob/47e2956a56edaa2450cb4c94be9f3ea70beae0c5/src/Utils/MODES.java#L1-L48

**Comment by 1chooo** [comment]
If we remove `final` from `MODES` it will occur the errors -- `case expressions must be constant expressions` that we use the `switch-case` to change the state; however, the `enum` should be added `final`. We still need to research, or we may need to rewrite the `switch-case` to `if-else` logic gate.

**Comment by alexeyleping** [comment]
change https://github.com/1chooo/uml-editor/pull/18
