### ISSUE TITLE
[Bug] The loading of icon lossing

### ISSUE THREAD

**Issue by 1chooo** [1chooo/uml-editor#19]
Hi! @alexeyleping

I have merged #18, but all the icons have changed to `select.png`. We can't load the other icons successfully. Could you please fix this?

The current:

![Screenshot 2024-06-15 at 8 48 25 PM](https://github.com/1chooo/uml-editor/assets/94162591/d3b947d2-e18d-4bcf-980a-22f9bf7d7d54)

The expected: 

![](https://github.com/1chooo/uml-editor/raw/main/docs/imgs/cover.png)

- assigned: @alexeyleping
- related: #18, #15

**Comment by 1chooo** [comment]
Hi @alexeyleping

In the following code snippet, there is a bug where `mode` is incorrectly compared to itself using the `equals()` method. This results in the condition always being true, causing only the first `if` statement to be accessible.

https://github.com/1chooo/uml-editor/blob/f4621b4232c97dcd59709a339388250d948b174c/src/Utils/MODES.java#L29-L30

```java
if(mode.equals(mode)){ 
    return "imgs/select.png"; 
}
```

**Bug Fix:**

To fix this issue, we need to compare `mode` to the constant `SELECT` instead of itself. The corrected code should be:

```java
if(mode.equals(SELECT)){ 
    return "imgs/select.png"; 
}
```

This change ensures that the condition correctly checks if `mode` is equal to `SELECT`, allowing the subsequent `if` statements to be evaluated properly.

**Comment by alexeyleping** [comment]
Hi! @1chooo 
fix bug
https://github.com/1chooo/uml-editor/pull/20
